name: acceptance-test

on:
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Languages & Frameworks
        uses: ./.github/actions/install
        with:
          skip_dotnet_and_java: "true"

      - name: Run acceptance tests
        run: make test
        env:
          PULUMITEST_TEMP_DIR: ${{ github.workspace }}/test_temp
          PULUMITEST_RETAIN_FILES_ON_FAILURE: "true"

      - name: Upload test_temp directory on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: test_temp

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
