name: acceptance-test

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Languages & Frameworks
        uses: pulumi/pulumi-azure-native/.github/actions/install@master
        with:
          skip_dotnet_and_java: "true"

      - name: Run acceptance tests
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
